---
title: "Diagnostic performance of left ventricular mechanical dyssynchrony indices using cardiovascular magnetic resonance feature tracking"
classoption: review
author:
    - name: Daniel E Loewenstein MD
      affiliation: ki-ks
    - name: Bjön Wieslander MD PhD
      affiliation: ki-ks
    - name: Einar Heiberg PhD
      affiliation: lund
    - name: Jimmy Axelsson MD
      affiliation: ki-ks
    - name: Igor Klem MD
      affiliation: duke
    - name: Robin Nijveldt MD PhD
      affiliation: rad
    - name: Erik B Schelbert MSc MD
      affiliation: allina
    - name: Peder Sörensson MD PhD
      affiliation: ki-med
    - name: Andreas Sigfridsson PhD
      affiliation: ki-ks
    - name: David G Strauss MD
      affiliation: fda
    - name: Raymond J Kim MD
      affiliation: dcmr
    - name: Brett D Atwater MD
      affiliation: inova
      footnote: 1
    - name: Martin Ugander MD PhD
      email: martin.ugander@gmail.com
      affiliation: ki-ks,usyd
      correspondingauthor: true
      footnote: 1
address:
    - code: ki-ks
      address: "Department of Clinical Physiology, Karolinska University Hospital, and Karolinska Institutet, Solna, Stockholm, Sweden"
    - code: lund
      address: "Clinical Physiology, Department of Clinical Sciences Lund, Lund University, Skåne University Hospital, Lund, Sweden"
    - code: duke
      address: "Division of Cardiology, Duke University Medical Center, Durham, NC, USA"
    - code: rad
      address: "Department of Cardiology, Radboud University Medical Center, Nijmegen, the Netherlands"
    - code: allina
      address: "Minneapolis Heart Institute East, Allina Health, United Hospital, St. Paul, MN, USA"
    - code: ki-med
      address: "Department of Medicine Solna, Karolinska Institutet, and Department of Cardiology, Karolinska University Hospital, Solna, Stockholm, Sweden"
    - code: fda
      address: "Division of Applied Regulatory Science, Office of Clinical Pharmacology, Office of Translational Sciences, Center for Drug Evaluation and Research, U.S. Food and Drug Administration, Silver Spring, MD, USA"
    - code: dcmr
      address: "Duke Cardiovascular Magnetic Resonance Center, Duke University Medical Center, Durham, NC, USA"
    - code: inova
      address: "Section of Cardiac Electrophysiology, Inova Heart and Vascular Institute, Fairfax, VA, USA"
    - code: usyd
      address: "Kolling Institute, Royal North Shore Hospital, and University of Sydney, Sydney, Australia"
footnote:
    - code: 1
      text: "Equal contribution as last author"
bibliography: auxilliary/library-bibtex-version.bib
link-citations: true
link-bibliography: true
abstract: |
  Background:
  Cardiac imaging-based indices of left ventricular (LV) mechanical
  dyssynchrony have limited accuracy for predicting the response to cardiac
  resynchronization therapy (CRT). The aim of the study was to evaluate the
  diagnostic performance of mechanical dyssynchrony indices in a study population
  of patients with severely reduced ejection fraction and no LV myocardial scar
  assessed by cardiovascular magnetic resonance (CMR), and either left bundle
  branch block (LBBB) or normal QRS duration.
  Methods:
  We retrospectively identified 80
  patients from three centers, with LV ejection fraction (${\le}35$%), no scar by
  CMR late gadolinium enhancement, and either normal electrocardiographic QRS
  duration (${\le}120$ms) and normal frontal plane electrical axis (-30 to
  +90 degrees) (control, n=36), or LBBB by Strauss'
  criteria (LBBB, n=44). The CMR image data from these
  subjects is made publicly available as part of this publication. CMR feature
  tracking was used to derive circumferential strain in a midventricular
  short-axis cine image. Using circumferential strain, mechanical dyssynchrony
  was quantified as the circumferential uniformity ratio estimate (CURE) and the
  systolic stretch index (SSI), respectively.
  Results:
  Both CURE and SSI resulted in measures of mechanical dyssynchrony that were more
  severe (lower CURE, higher SSI) in LBBB compared to controls
  (CURE, median [interquartile range], 0.63 [0.54-0.75] vs 0.79 [0.69-0.86],
  p\textless0.001;
  SSI 9.4 [7.4-12.7] vs 2.2 [1.2-3.6],
  p\textless0.001).
  SSI outperformed CURE in the ability to discriminate between LBBB and controls
  (area under the receiver operating characteristics curve [95\% confidence interval]
  0.98 [0.95-1.00] vs 0.77 [0.66-0.86],
  p\textless0.001;
  sensitivity 93 [84-100]
  vs 75 [61-86] \%,
  p=0.02; specificity 97 [92-100]
  vs 67 [50-81] \%,
  p=0.003).
  Conclusions:
  The ability to discriminate between LBBB and normal QRS duration
  among patients with severely reduced ejection fraction and no scar was fair for
  CURE and excellent for SSI.
keywords:
    - Cardiac Magnetic Resonance
    - Mechanical Dyssynchrony
    - Left Bundle Branch Block
    - Cardiac Resynchronization Therapy
    - Heart Failure
    - Circumferential Strain
header-includes:
  - \usepackage{relsize}
  - \usepackage[T1]{fontenc}
  - \usepackage{placeins}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include=FALSE)
```

```{r}
library(dplyr, quietly = TRUE)
library(ggplot2, quietly = TRUE)
```

```{r}
# Set paths
PROJECT_DIR <- rprojroot::find_rstudio_root_file()
RAW_DATA_DIR <- file.path(PROJECT_DIR, "analysis", "data", "raw_data")
DERIVED_DATA_DIR <- file.path(PROJECT_DIR, "analysis", "data", "derived_data")
FIG_DIR <- file.path(PROJECT_DIR, "analysis", "figures")
```

```{r}
dillacs <- readRDS(file.path(DERIVED_DATA_DIR, "dyssynchrony_data.Rds"))
stats <- readRDS(file.path(DERIVED_DATA_DIR, "statistics.Rds"))
figs  <- readRDS(file.path(DERIVED_DATA_DIR, "figs.Rds"))
source(file.path(PROJECT_DIR, "R", "offset2groups.R"))
```

```{r}
pval_print <- function(x) {
    if (x < 0.001)
        paste("\U003C", "0.001", sep = "")
    else if (x < 0.01)
        sprintf("=%.3f", x)
    else
        sprintf("=%.2f", x)
}
```

```{r}
LBBB <- filter(dillacs, lbbb1_control0 == "LBBB")
Control <- filter(dillacs, lbbb1_control0 == "Control")

print_m_iqr <- function(var, data) {
    d <- data[[var]]
    m <- median(d)
    q1 <- quantile(d, 0.25)
    q3 <- quantile(d, 0.75)
    
    if (var == "cure") {
        sprintf("%.2f [%.2f-%.2f]", m, q1, q3)
    } else {
        sprintf("%.1f [%.1f-%.1f]", m, q1, q3)
    }
}

print_auc_ci <- function(var) {
    auc <- stats[[var]]$auc
    ci_lower <- stats[[var]]$auc_ci["2.5%"]
    ci_upper <- stats[[var]]$auc_ci["97.5%"]
    sprintf("%.2f [%.2f-%.2f]", auc, ci_lower, ci_upper)
}

cure_wilcox_pval <- (wilcox.test(cure ~ lbbb1_control0, data = dillacs))$p.value
ssi_wilcox_pval  <- (wilcox.test(ssi ~ lbbb1_control0, data = dillacs))$p.value

as_percent <- function(x) 100*x

stats$cure$sens <- as_percent(stats$cure$sens)
stats$cure$spec <- as_percent(stats$cure$spec)
stats$cure$cisens <- as_percent(stats$cure$cisens)
stats$cure$cispec <- as_percent(stats$cure$cispec)
stats$ssi$sens <- as_percent(stats$ssi$sens)
stats$ssi$spec <- as_percent(stats$ssi$spec)
stats$ssi$cisens <- as_percent(stats$ssi$cisens)
stats$ssi$cispec <- as_percent(stats$ssi$cispec)

```
<!-----------------------------------------------------------------------------
# Abstract

*Background:* Cardiac imaging-based indices of left ventricular (LV) mechanical
dyssynchrony have limited accuracy for predicting the response to cardiac
resynchronization therapy (CRT). The aim of the study was to evaluate the
diagnostic performance of mechanical dyssynchrony indices in a study population
of patients with severely reduced ejection fraction and no LV myocardial scar
assessed by cardiovascular magnetic resonance (CMR), and either left bundle
branch block (LBBB) or normal QRS duration.
*Methods:* We retrospectively identified `r length(unique(dillacs$id))`
patients from three centers, with LV ejection fraction ${\le}{35}$%, no scar by
CMR late gadolinium enhancement, and either normal electrocardiographic QRS
duration (${<}120$ms) and normal frontal plane electrical axis (-30 to
+90 degrees) (control, `r sprintf("n=%d", nrow(Control))`), or LBBB by Strauss'
criteria (LBBB, `r sprintf("n=%d", nrow(LBBB))`). The CMR image data from these
subjects is made publicly available as part of this publication. CMR feature
tracking was used to derive circumferential strain in a midventricular
short-axis cine image. Using circumferential strain, mechanical dyssynchrony
was quantified as the circumferential uniformity ratio estimate (CURE) and the
systolic stretch index (SSI), respectively.
*Results:* Both CURE and SSI resulted in measures of mechanical dyssynchrony that were more
severe (lower CURE, higher SSI) in LBBB compared to controls
(CURE, median [interquartile range], `r print_m_iqr("cure", LBBB)` vs `r print_m_iqr("cure", Control)`,
p`r pval_print(cure_wilcox_pval)`; 
SSI `r print_m_iqr("ssi", LBBB)` vs `r print_m_iqr("ssi", Control)`,
p`r pval_print(ssi_wilcox_pval)`). 
SSI outperformed CURE in the ability to discriminate between LBBB and controls
(area under the receiver operating characteristics curve [95% confidence interval]
`r print_auc_ci("ssi")` vs `r print_auc_ci("cure")`, 
p`r pval_print(stats$compare_auc$p.value)`; 
sensitivity `r sprintf("%.0f [%.0f-%.0f]", stats$ssi$sens, stats$ssi$cisens["2.5%"], stats$ssi$cisens["97.5%"])` 
vs `r sprintf("%.0f [%.0f-%.0f] %%", stats$cure$sens, stats$cure$cisens["2.5%"], stats$cure$cisens["97.5%"])`,
`r sprintf("p%s", pval_print(stats$sens_xmcnemar))`; specificity `r sprintf("%.0f [%.0f-%.0f]", stats$ssi$spec, stats$ssi$cispec["2.5%"], stats$ssi$cispec["97.5%"])`
vs `r sprintf("%.0f [%.0f-%.0f] %%", stats$cure$spec, stats$cure$cispec["2.5%"], stats$cure$cispec["97.5%"])`,
`r sprintf("p%s", pval_print(stats$spec_xmcnemar))`).
*Conclusions:* The ability to discriminate between LBBB and normal QRS duration
among patients with severely reduced ejection fraction and no scar was fair for
CURE and excellent for SSI.
----------------------------------------------------------------------------->
